apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-backend
  labels:
    app: myapp-backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: myapp-backend
  template:
    metadata:
      labels:
        app: myapp-backend
    spec:
      containers:
      - name: http-echo
        image: {{ .Values.backend.image }}
        args:
{{- toYaml .Values.backend.args | nindent 10 }}
        ports:
        - containerPort: 5678
        resources:
{{- toYaml .Values.backend.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-backend
spec:
  selector:
    app: myapp-backend
  ports:
  - name: http
    port: 5678
    targetPort: 5678
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-backend
  labels:
    app: myapp-backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: myapp-backend
  template:
    metadata:
      labels:
        app: myapp-backend
    spec:
      containers:
      - name: http-echo
        image: {{ .Values.backend.image }}
        args:
{{- toYaml .Values.backend.args | nindent 10 }}
        ports:
        - containerPort: 5678
        resources:
{{- toYaml .Values.backend.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-backend
spec:
  selector:
    app: myapp-backend
  ports:
  - name: http
    port: 5678
    targetPort: 5678

