apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: LimitRange
  metadata:
    name: app-defaults
    namespace: applications
  spec:
    limits:
    - default:
        cpu: "300m"
        memory: "256Mi"
      defaultRequest:
        cpu: "50m"
        memory: "64Mi"
      type: Container
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: app-quota
    namespace: applications
  spec:
    hard:
      requests.cpu: "2"
      requests.memory: 2Gi
      limits.cpu: "4"
      limits.memory: 4Gi
